/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.boot;

import org.hamcrest.Matchers;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertThat;

@RunWith(SpringRunner.class)
@SpringBootTest
public class AppTest {

    @Autowired
    private App controller;

    @Test
    public void testAppHasAGreeting() {
        assertNotNull(controller);
        assertThat(controller.getGreeting(), Matchers.equalTo("Hello, world"));
    }
}
